services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    volumes:
      - ./lt-data:/home/libretranslate/.local
    restart: unless-stopped

  proxy:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      LT_URL: "http://libretranslate:5000"
      PORT: "5000"
    depends_on:
      - libretranslate
    restart: unless-stopped
